<a href="https://colab.research.google.com/github/jindehuang1/ml2dl_huang/blob/main/lx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.constant([[1,2,3],[1,2,3]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [3]:
tf.random.normal(shape=(2,3),mean=0,stddev=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-3.0531585, -0.8747491, -0.1004406],
       [-0.702547 , -1.4938601,  0.5855736]], dtype=float32)>

In [5]:
tf.argmax(tf.constant([1,2,3]))

<tf.Tensor: shape=(), dtype=int64, numpy=2>